version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      development:
        patterns: ["ruff", "mypy", "pytest*", "types-*"]
    open-pull-requests-limit: 5
