blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/damien-robotsix/robotsix-yaml-config/discussions
    about: Please ask usage questions in GitHub Discussions.
