name: Deps Bump

on:
  schedule:
    - cron: "0 6 * * 1"   # every Monday 06:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deps-bump:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/deps-bump.yml@5cd8c1facb02299da618979e7a55f1953f9c075a
    permissions:
      contents: write
      pull-requests: write
    secrets:
      DEPS_BUMP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
