name: Docs
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/python-docs.yml@1b8dc25d58397aef057b2a3d98722cbd10f23653
    with:
      docs-install-args: "--extra dev"
    secrets: {}
