name: Docs
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    uses: damien-robotsix/robotsix-mill/.github/workflows/python-docs.yml@a063c729739539138db80ce72c82a35e38eb76f9
    with:
      docs-install-args: "--extra dev"
    secrets: inherit
