name: Lint Workflows

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/lint-workflows.yml@56a5aa3eb6b72a6d6b16bb6a227e2c9d707ec397
    with:
      run-actionlint: true
      run-zizmor: true
