name: Lint Workflows

on:
  push:
  pull_request:

permissions: read-all

jobs:
  lint:
    permissions:
      contents: read
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/lint-workflows.yml@7314c9b6c2b536ca81023e8841f272b72733262e
    with:
      run-actionlint: true
      run-zizmor: true
